In [1]:
import pandas as pd
import numpy as np

In [8]:
import os
print(os.getcwd())

C:\Users\goyle\Desktop\bdumlalgorithms\Classification

In [25]:
data = pd.read_csv('C:\\Users\\goyle\\Desktop\\bdumlalgorithms\\Regression\\Dynamic Pricing.csv')

In [26]:
data

,trip_id,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,City,passenger_count,pickup_day,pickup_month,pickup_year,pickup_hour,pickup_minute,pickup_second,fare_amount
0,1,-73.844315,40.721317,-73.841610,40.712276,New York,1,15,6,2009,17,26,21,4.5
1,2,-74.016045,40.711304,-73.979270,40.782005,New York,1,5,1,2010,16,52,16,16.9
2,3,-73.982735,40.761270,-73.991240,40.750560,New York,2,18,8,2011,0,35,0,5.7
3,4,-73.987130,40.733143,-73.991570,40.758090,New York,1,21,4,2012,4,30,42,7.7
4,5,-73.968094,40.768010,-73.956660,40.783764,New York,1,9,3,2010,7,51,0,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49996,-73.999970,40.748530,-74.016900,40.705994,New York,1,12,6,2013,23,25,15,15.0
49996,49997,-73.984760,40.768210,-73.987366,40.760597,New York,1,22,6,2015,17,19,18,7.5
49997,49998,-74.002700,40.739430,-73.998110,40.759483,New York,1,30,1,2011,4,53,0,6.9
49998,49999,-73.946060,40.777570,-73.953450,40.779686,New York,2,6,11,2012,7,9,0,4.5
49999,50000,-73.932600,40.763805,-73.932600,40.763805,New York,1,13,1,2010,8,13,14,10.9

In [28]:
del data['City']

In [29]:
data

,trip_id,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,pickup_day,pickup_month,pickup_year,pickup_hour,pickup_minute,pickup_second,fare_amount
0,1,-73.844315,40.721317,-73.841610,40.712276,1,15,6,2009,17,26,21,4.5
1,2,-74.016045,40.711304,-73.979270,40.782005,1,5,1,2010,16,52,16,16.9
2,3,-73.982735,40.761270,-73.991240,40.750560,2,18,8,2011,0,35,0,5.7
3,4,-73.987130,40.733143,-73.991570,40.758090,1,21,4,2012,4,30,42,7.7
4,5,-73.968094,40.768010,-73.956660,40.783764,1,9,3,2010,7,51,0,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49996,-73.999970,40.748530,-74.016900,40.705994,1,12,6,2013,23,25,15,15.0
49996,49997,-73.984760,40.768210,-73.987366,40.760597,1,22,6,2015,17,19,18,7.5
49997,49998,-74.002700,40.739430,-73.998110,40.759483,1,30,1,2011,4,53,0,6.9
49998,49999,-73.946060,40.777570,-73.953450,40.779686,2,6,11,2012,7,9,0,4.5
49999,50000,-73.932600,40.763805,-73.932600,40.763805,1,13,1,2010,8,13,14,10.9

In [30]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [32]:
X = data[['pickup_longitude', 'pickup_latitude', 'dropoff_longitude','dropoff_latitude','passenger_count','pickup_day','pickup_month','pickup_year','pickup_hour','pickup_minute','pickup_second']]

y = data['fare_amount']

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [35]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [36]:
y_pred = model.predict(X_test)

In [37]:
from sklearn.metrics import mean_squared_error, r2_score

In [38]:
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [39]:
print("Mean Squared Error:", mse)
print("R-squared:", r2)

Mean Squared Error: 87.30103370886216
R-squared: 0.021592634781227527

In [40]:
print(data.dtypes)

trip_id                int64
pickup_longitude     float64
pickup_latitude      float64
dropoff_longitude    float64
dropoff_latitude     float64
passenger_count        int64
pickup_day             int64
pickup_month           int64
pickup_year            int64
pickup_hour            int64
pickup_minute          int64
pickup_second          int64
fare_amount          float64
dtype: object

In [41]:
print(data.describe())

            trip_id  pickup_longitude  pickup_latitude  dropoff_longitude  \
count  50000.000000      50000.000000     50000.000000       50000.000000
mean   25000.500000        -72.509756        39.933759         -72.504616
std    14433.901067         10.393860         6.224857          10.407570
min        1.000000        -75.423850       -74.006890         -84.654240
25%    12500.750000        -73.992065        40.734880         -73.991150
50%    25000.500000        -73.981840        40.752678         -73.980080
75%    37500.250000        -73.967150        40.767360         -73.963585
max    50000.000000         40.783470       401.083340          40.851030

       dropoff_latitude  passenger_count    pickup_day  pickup_month  \
count      50000.000000     50000.000000  50000.000000  50000.000000
mean          39.926251         1.667840     15.672040      6.273300
std            6.014737         1.289195      8.660789      3.461157
min          -74.006380         0.000000      1.000000      1.000000
25%           40.734370         1.000000      8.000000      3.000000
50%           40.753372         1.000000     16.000000      6.000000
75%           40.768166         2.000000     23.000000      9.000000
max           43.415190         6.000000     31.000000     12.000000

        pickup_year   pickup_hour  pickup_minute  pickup_second   fare_amount
count  50000.000000  50000.000000   50000.000000   50000.000000  50000.000000
mean    2011.739260     13.489080      29.665420      15.871900     11.351449
std        1.862639      6.506935      17.306535      19.429542      9.529177
min     2009.000000      0.000000       0.000000       0.000000     -5.000000
25%     2010.000000      9.000000      15.000000       0.000000      6.000000
50%     2012.000000     14.000000      30.000000       4.000000      8.500000
75%     2013.000000     19.000000      45.000000      32.000000     12.500000
max     2015.000000     23.000000      59.000000      59.000000    100.000000

In [42]:
del data['trip_id']

In [43]:
data

,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,pickup_day,pickup_month,pickup_year,pickup_hour,pickup_minute,pickup_second,fare_amount
0,-73.844315,40.721317,-73.841610,40.712276,1,15,6,2009,17,26,21,4.5
1,-74.016045,40.711304,-73.979270,40.782005,1,5,1,2010,16,52,16,16.9
2,-73.982735,40.761270,-73.991240,40.750560,2,18,8,2011,0,35,0,5.7
3,-73.987130,40.733143,-73.991570,40.758090,1,21,4,2012,4,30,42,7.7
4,-73.968094,40.768010,-73.956660,40.783764,1,9,3,2010,7,51,0,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...
49995,-73.999970,40.748530,-74.016900,40.705994,1,12,6,2013,23,25,15,15.0
49996,-73.984760,40.768210,-73.987366,40.760597,1,22,6,2015,17,19,18,7.5
49997,-74.002700,40.739430,-73.998110,40.759483,1,30,1,2011,4,53,0,6.9
49998,-73.946060,40.777570,-73.953450,40.779686,2,6,11,2012,7,9,0,4.5
49999,-73.932600,40.763805,-73.932600,40.763805,1,13,1,2010,8,13,14,10.9

In [44]:
print(data.isnull().sum())

pickup_longitude     0
pickup_latitude      0
dropoff_longitude    0
dropoff_latitude     0
passenger_count      0
pickup_day           0
pickup_month         0
pickup_year          0
pickup_hour          0
pickup_minute        0
pickup_second        0
fare_amount          0
dtype: int64

In [75]:
a = data.iloc[1, 0:11]
print(a)

pickup_longitude      -74.016045
pickup_latitude        40.711304
dropoff_longitude     -73.979270
dropoff_latitude       40.782005
passenger_count         1.000000
pickup_day              5.000000
pickup_month            1.000000
pickup_year          2010.000000
pickup_hour            16.000000
pickup_minute          52.000000
pickup_second          16.000000
Name: 1, dtype: float64

In [76]:
print(model.predict(a.to_frame().T))

[9.30947685]

In [77]:
data

,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,pickup_day,pickup_month,pickup_year,pickup_hour,pickup_minute,pickup_second,fare_amount
0,-73.844315,40.721317,-73.841610,40.712276,1,15,6,2009,17,26,21,4.5
1,-74.016045,40.711304,-73.979270,40.782005,1,5,1,2010,16,52,16,16.9
2,-73.982735,40.761270,-73.991240,40.750560,2,18,8,2011,0,35,0,5.7
3,-73.987130,40.733143,-73.991570,40.758090,1,21,4,2012,4,30,42,7.7
4,-73.968094,40.768010,-73.956660,40.783764,1,9,3,2010,7,51,0,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...
49995,-73.999970,40.748530,-74.016900,40.705994,1,12,6,2013,23,25,15,15.0
49996,-73.984760,40.768210,-73.987366,40.760597,1,22,6,2015,17,19,18,7.5
49997,-74.002700,40.739430,-73.998110,40.759483,1,30,1,2011,4,53,0,6.9
49998,-73.946060,40.777570,-73.953450,40.779686,2,6,11,2012,7,9,0,4.5
49999,-73.932600,40.763805,-73.932600,40.763805,1,13,1,2010,8,13,14,10.9

In [78]:
import seaborn as sns